### ISSUE TITLE
[DSFT 1기 개인 블로그 목록]

### ISSUE THREAD

**Issue by jhk0530** [codestates/ds-blog#99]
- 김가연 <https://velog.io/@gayeon>
- 김민채 <https://medium.com/@sutjr1013>
- 김현재 <https://medium.com/@jalynne_kim>
- 문승태 <https://medium.com/@conanmoon>
- 송지 <https://medium.com/@jisong830>
- 오세광 <https://medium.com/@osktr5>
- 오예은 <https://medium.com/@dsdoris>
- 이동훈 <https://medium.com/@kroonstazy>
- 이선주 <https://velog.io/@seonj102>
- 이윤회 <https://medium.com/@ubrain0624>
- 이재우 <https://jaewoo4710.github.io>
- 이중호 <https://medium.com/@lastmanjh91>
- 정유태 <https://yut-a.github.io/>
- 조보현 <https://bohyuncho.github.io>

빠진 분 있으면 알려주세요.

**Comment by bohyuncho** [comment]
아직 정리중이지만, 여기있어요 : https://bohyuncho.github.io

**Comment by jingwoo4710** [comment]
저도 있습니다. [https://jaewoo4710.github.io](https://jaewoo4710.github.io/)
